def fibonacci(limit)
  fib = [1, 2]
  count = 2
  if limit > 2
    while count <= limit do
      if count == fib[-1] + fib[-2]
        fib << count
      end
      count += 1
    end
  end
  fib
end

def even_fibonacci_sum(limit)
  fib = fibonacci(limit)
  fib.select {|num| num.even? }.inject(:+)
end

# - Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#     - 1,2,3,5,8,13,21,34,55,89...
# - By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
