def even_fibonacci_sum(limit)
  fib = [1, 2]
  if limit > 3
    num_arr = [*3..limit]
    num_arr.each_with_index do |num, index|
      fib << num if num == (fib[index-1] + fib[index-2])
    end
  end
end

# - Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#     - 1,2,3,5,8,13,21,34,55,89...
# - By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
